# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'

# Binaries
brew 'awscli'
brew 'bash' # Latest Bash version
brew 'coreutils' # Those that come with macOS are outdated
brew 'gh'
brew 'git'
brew 'git-flow'
brew 'gnupg'
brew 'grep'
brew 'httpie'
brew 'hub'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'stripe/stripe-cli/stripe'
brew 'svn'
brew 'trash' # Manage the Trash bin
brew 'tree' # List directories in a tree structure
brew 'zlib' # Needed for Memcached

# Spatie Medialibrary
brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'

# Development
brew 'php'
brew 'php@7.4'
brew 'composer'
brew 'imagemagick'
brew 'libmemcached'
brew 'meilisearch'
brew 'memcached'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'redis'
brew 'yarn'

# Apps
cask '1password'
cask 'caffeine'
cask 'dbngin'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'google-drive'
cask 'gpg-suite'
cask 'imageoptim'
cask 'insomnia'
cask 'pastebot'
cask 'phpmon'
cask 'phpstorm'
cask 'ray'
cask 'screenflow'
cask 'signal'
cask 'slack'
cask 'tableplus'
cask 'telegram-desktop'
cask 'terraform'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'transmit'
cask 'tunnelbear'
cask 'tuple'
cask 'visual-studio-code'
cask 'zoom'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
